#!/usr/bin/env bash

if [[ -z "${1}" || ! ("${@}" =~ '-k' || "${@}" =~ '-m') || $# -lt 2 ]]; then
    echo "usage: remote [<device>] -k <key> | -m <message>"
    exit 1
fi

if [[ "${1}" =~ ^-[km] ]]; then
    op="${1}" 
else
    ROKU_IP="${1}"
    op="${2}"
fi

[ -n "${ROKU_IP}" ] || ROKU_IP=""
[[ -z "${ROKU_IP}" || "${ROKU_IP}" =~ ^([0-9a-fA-F]{4}:){7}[0-9a-fA-F]{4}$ || \
    "${ROKU_IP}" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || \
    ROKU_IP=$(awk "!/^[[:space:]]*#/ && /${ROKU_IP//\//\\/}/ { print \$1 }" </etc/hosts)
[ -z "${ROKU_IP}" ] && echo 'error: invalid hostname/ip' >&2 && exit 1

msg=$(sed 's/^.*-[mk] *//' <<<"${@}")

if [ "${op}" = '-k' ]; then
    curl -s -d '' "${ROKU_IP}:8060/keypress/${msg}"
else
    len=${#msg}

    for (( pos=0 ; pos<len ; pos++ )); do
        c=${msg:$pos:1}
        case "$c" in
        [-_.~a-zA-Z0-9] ) o="${c}" ;;
        * )               printf -v o '%%%02x' "'$c"
        esac
        curl -s -d '' "${ROKU_IP}:8060/keypress/Lit_${o}"
    done
fi
